Repository ffoodd/a11y.css, pull requests merged in 2021-01, with the labels that each got.

#401 Added Spanish language
  .travis.yml
  css/a11y-es.css
  css/a11y-es_error.css
  css/a11y-es_obsolete.css
  css/a11y-es_warning.css
  locales/es.json
  sass/a11y-es.scss
  sass/a11y-es_error.scss
  sass/a11y-es_obsolete.scss
  sass/a11y-es_warning.scss
  sass/locales/_es.scss
  tasks/helpers/options.js
Labels: enhancement, translation

#402 Added Spanish to WebExtension
  webextension/scripts/locales.js
Labels: enhancement, translation, webextension

#414 Add a few references to newer tests
  sass/themes/_error.scss
Labels: documentation, enhancement
